### ISSUE TITLE
sum of Gridworld.transition_probability is not 1

### ISSUE THREAD

**Issue by yosh7of9** [MatthewJA/Inverse-Reinforcement-Learning#1]
`gw = gridworld.Gridworld(5, .3, .2)`
`gw.transition_probability[7,0,:].reshape(5,5)`

outputs

`array([`
`[ 0.   ,  0.   ,  0.075,  0.   ,  0.   ],`
`[ 0.   ,  0.075,  0.075,  0.775,  0.   ],`
`[ 0.   ,  0.   ,  0.075,  0.   ,  0.   ],`
`[ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ],`
`[ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ]])`

But  should sum of  this  be 1 ?

**Comment by MatthewJA** [comment]
Ah, good catch! I'll have a shot at fixing this shortly.
