### ISSUE TITLE
Broken Report Link

### ISSUE THREAD

**Issue by OculusMode** [MatthewJA/Inverse-Reinforcement-Learning#12]
Hello,
The report link in Readme.md is broken, it'd be great to me and future readers if it's updated to read how the algorithm works.

Thanks.

**Comment by OculusMode** [comment]
Oh, I've just found the correct link.
Here's the pull request for the same.
https://github.com/MatthewJA/Inverse-Reinforcement-Learning/pull/13

**Comment by MatthewJA** [comment]
Much appreciated. Resolved by #13
