### ISSUE TITLE
super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by xinleipan** [MatthewJA/Inverse-Reinforcement-Learning#3]
File "../irl/mdp/objectworld.py", line 56, in __init__
    super().__init__(grid_size, wind, discount)
TypeError: super() takes at least 1 argument (0 given)

Could anyone give any help?

**Comment by MatthewJA** [comment]
Are you using Python 3?

**Comment by xinleipan** [comment]
Thanks Matthew! I'm using python 2.7. However, when I directly run maxent_gridworld.py it works fine. But "maxent_objectworld.py" does not work well...

**Comment by MatthewJA** [comment]
The code is for Python 3 only &mdash; as you've found, it *might* work on Python 2, but only by coincidence. I recommend Python 3.4+.
