### ISSUE TITLE
MaxEnt Efficient State Frequency Calculation

### ISSUE THREAD

**Issue by chenyucheng2016** [MatthewJA/Inverse-Reinforcement-Learning#7]
According to Ziebart's paper, the equation that updates the state visit frequency is as follows:
![image](https://user-images.githubusercontent.com/20000790/46920343-d63d2c00-cfba-11e8-97aa-0fe224e1e24d.png)
So, I think the implementation should be:
` expected_svf[i, t] += (expected_svf[k, t-1] *
                                  policy[i, j] * # Stochastic policy
                                  transition_probability[i, j, k])`

**Comment by unhelkar** [comment]
Hi @chenyucheng2016 , Nice catch! However, I think the computation of `expected_svf` is correct. Instead there is a typo in the equation. For more details, please see the note at this [link](http://www.cs.cmu.edu/~bziebart/publications/maximum-entropy-inverse-reinforcement-learning.html).

**Comment by chenyucheng2016** [comment]
Hi @unhelkar , thank you very much for sharing the corrected version of the paper!
